[tool.poetry]
name = "stapler"
version = "1.1.0"
description = "Manipulate PDF documents from the command line"
authors = ["Philip Stark", "Fred Wenzel"]
license = "BSD-3-Clause"
readme = 'README.rst'
repository = "https://github.com/hellerbarde/stapler"
packages = [
    { include = "staplelib" },
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/hellerbarde/stapler/issues"

[tool.poetry.dependencies]
python = "^3.7"
pypdf = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "*"
tox = "^3.14"
tox-pyenv = "^1.1"

[tool.poetry.scripts]
stapler = 'staplelib:main'
pdf-stapler = 'staplelib:main'

# this section is for PEP517 compliance. It is technically unnecessary if using Poetry
[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
